# Практическая работа 14 (Тест)
## Тема: Задача регрессии

### Настройка окружения

In [1]:
import pandas as pd
import numpy as np

### Вопрос 1
Дан [набор данных](./data9.csv), содержащий некоторые входные данные (**x**), реальные данные (**y_true**) и зашумленные данные (**y**) для зависимости $y = 6x+8$:

<p align="center">
    <img src="task_1.png" alt="График зависимости" width="400">
</p>

Попробуем по зашумленным данным выполнить аппроксимацию линейной зависимости и оценим качество путём сравнения с реальными данными.

Для этого:

0. Загрузим набор данных.

In [3]:
data = pd.read_csv("data5.csv")
data.head()

          x          y     y_true
0  0.000000   8.960570   3.000000
1  0.606061   3.765071   5.424242
2  1.212121  15.620747   7.848485
3  1.818182  28.549086  10.272727
4  2.424242   9.887129  12.696970

1. Составим матрицу $X$, первый столбец которой будет состоять из единиц, а второй - содержать значения входных данных $x$.

In [4]:
x = data["x"]

X = np.vstack([np.ones(len(x)), x]).T

2. Запишем зашумленные данные в вектор $y$.

In [5]:
y = data["y"]

3. Найдём значения вектора весов $w$ по формуле из лекции: $w = (X^TX)^{-1}X^Ty$

In [6]:
XT_X = X.T @ X
XT_X_inv = np.linalg.inv(XT_X)

w = XT_X_inv @ X.T @ y

- Укажите элемент с координатами $[0, 0]$ в обратной матрице $(X^TX)^{-1}$, значение округлите до 3-х знаков после запятой:

In [7]:
round(XT_X_inv[0, 0], 3)

np.float64(0.039)

- Укажите получившиеся значения матрицы весов $w$, округлённые до 2 знаков после запятой.

In [8]:
w.round(2)

array([0.93, 4.03])

4. Оцените качество аппроксимации с использованием метрики MSE. Получившееся значение округлите до 2-х знаков после запятой:

In [9]:
y_pred = X @ w
y_true = data["y_true"]

mse = np.mean((y_true - y_pred) ** 2)

round(mse, 2)

np.float64(1.79)

### Вопрос 2
Дан [набор данных](./data21.csv), содержащий некоторые входные данные (**x**), реальные данные (**y_true**) и зашумленные данные (**y**) для зависимости $y = 2x - x^2 + 2x^3 - 1$:

<p align="center">
    <img src="task_2.png" alt="График зависимости" width="400">
</p>

Попробуем по зашумленным данным выполнить аппроксимацию полиномиальной зависимости и оценим качество путём сравнения с реальными данными.

Для этого:

0. Загрузим набор данных.

In [10]:
data = pd.read_csv("data21.csv")
data.head()

         x         y    y_true
0  0.00000 -0.960263 -1.000000
1  0.00502 -1.016031 -1.004970
2  0.01004 -0.958025 -1.009841
3  0.01506 -0.892771 -1.014613
4  0.02008 -1.038022 -1.019290

1. Составим матрицу $X$, первый столбец которой будет состоять из единиц, второй содержать значения входных данных $x$, третий - значения $x^2$, четвёртый - значения $x^3$.

In [11]:
x = data["x"]
x2 = x ** 2
x3 = x ** 3

X = np.vstack([np.ones(len(x)), x, x2, x3]).T

2. Запишем зашумленные данные в вектор $y$.

In [12]:
y = data["y"]

3. Найдём значения вектора весов $w$ по формуле из лекции: $w = (X^TX)^{-1}X^Ty$

In [13]:
XT_X = X.T @ X
XT_X_inv = np.linalg.inv(XT_X)

w = XT_X_inv @ X.T @ y

- Укажите элемент с координатами $[3, 0]$ в обратной матрице $(X^TX)^{-1}$, значение округлите до 2-х знаков после запятой:

In [14]:
round(XT_X_inv[0, 1], 2)

np.float64(-0.37)

- Укажите получившиеся значения матрицы весов $w$, округлённые до 2 знаков после запятой.

In [15]:
w.round(2)

array([-1.01, -1.07,  2.2 , -2.11])

4. Оцените качество аппроксимации с использованием метрики MSE. Получившееся значение округлите до 3-х знаков после запятой:

In [16]:
y_pred = X @ w
y_true = data["y_true"]

mse = np.mean((y_true - y_pred) ** 2)

round(mse, 5)

np.float64(7e-05)

### Бизнес-постановка задачи
Для правильной разработки, проектирования, выбора типоразмера и изготовления установок электрогазоочистки, правильной пуско-наладки и эксплуатации электрофильтров (ЭФ) необходимо учитывать свойства улавливаемой пыли. А накопление большого слоя пыли вокруг электрочувствительных аппаратов может приводить к перебоям в их работе и аварийным ситуациям.

### Постановка задачи анализа данных
Целью данной задачи является прогнозирование значения удельного электрического сопротивления пыли с помощью построения регрессионных моделей и их анализа. Зависимость УЭС пыли от температуры, влажности, дисперсного и химического состава пыли и газов и от других параметров используется в расчете скорости дрейфа улавливаемых частиц. Знание величины УЭС пыли требуется для подготовки газов перед электрофильтрами, при определении рациональных режимных параметров работы ЭФ для интенсификации процесса пылеулавливания.

### Обзор доступных данных
В выборке 360 наблюдений и 10 переменных.

[Набор данных](./dust.xlsx) содержит два типа переменных:
- целевая: **resistivity**, УЭС пыли;
- остальные переменные: 9 переменных, могут использоваться для прогноза целевой переменной.

<p align="center">
    <img src="dust_columns.png" alt="Таблица имен столбцов и их значений" width="400">
</p>

Таким образом, про каждое из 360 значений удельного электрического сопротивления мы знаем значения 9 его характеристик (температура, влажность, плотность пылевого слоя, размер частиц и т.д.).

In [17]:
dust_data = pd.read_excel("dust.xlsx")
dust_data.head()

,resistivity,temperature,humidity,density,dust_capacity,particle_size,is_chelyabinsk,conductivity,dust_dispersiveness,formation
0,74842.750101,25,1.52,1158.853782,2.373993,22.647043,1.0,average,coarse visible,decomposition
1,34527.969004,25,1.52,1272.135396,2.363867,11.526920,NaN,average,coarse visible,decomposition
2,5906.170844,25,1.52,1478.310822,2.347559,12.600888,1.0,average,coarse visible,decomposition
3,69134.819557,25,1.52,1214.674362,2.368885,8.052817,1.0,average,coarse microscopic,decomposition
4,22697.480968,25,1.52,1299.579609,2.361549,48.875257,NaN,average,coarse visible,decomposition

### Вопрос 3
Определим наличие пропусков в наборе данных. В качестве ответа укажите кол-во пропусков в столбце **is_chelyabinsk**.

In [18]:
dust_data["dust_capacity"].isnull().sum()

np.int64(12)

В столбце **is_chelyabinsk**, указывающем на место получения образца пыли, порядка 30% пропущенных значений. Если предположить, что свойства пыли (химический состав) для различных образцов не отличаются, то мы можем избавиться от данной колонки.

In [19]:
dust_data = dust_data.drop(columns=["is_chelyabinsk"])

Заполним пропуски в столбце **dust_capacity** средним значением ёмкости пыли.

In [20]:
dust_capacity_mean = dust_data["dust_capacity"].mean()

dust_data["dust_capacity"] = dust_data["dust_capacity"].fillna(dust_capacity_mean)

После обработки пропусков убедитесь, что их больше не осталось в датафрейме.

In [23]:
dust_data.isnull().any().any()

np.False_

### Вопрос 4
Укажите кол-во категориальных признаков.

In [24]:
categorical_columns = dust_data.select_dtypes(include=["object", "category"]).columns

len(categorical_columns)

/var/folders/fs/l607bnnd1cgg08pttn0yqbyh0000gn/T/ipykernel_29842/386929768.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = dust_data.select_dtypes(include=["object", "category"]).columns

3

### Вопрос 5
Выполним кодирование категориальных признаков с использованием прямого кодирования (*Label Encoding*). Кодирование выполните с помощью библиотеки `sklearn`, нумерацию категорий начните с 1 (не с 0 как по умолчанию). В качестве ответа укажите кол-во значений во 2 категории признака **formation**.

In [25]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in categorical_columns:
    dust_data[col] = le.fit_transform(dust_data[col]) + 1

(dust_data["dust_dispersiveness"] == 3).sum()

np.int64(5)

### Вопрос 6
Разделим набор данных на обучающую и тестовую выборки для построения модели линейной регрессии:

In [26]:
from sklearn.model_selection import train_test_split

X = dust_data.drop(columns=["resistivity"])
y = dust_data["resistivity"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

Далее выполним создание и обучение модели линейной регрессии, которая будет предсказывать УЭС пыли (**resistivity**) в зависимости от значений всех остальных предикторов. В качестве ответа укажите значение свободного члена, округлённое до 2 знаков после запятой.

In [33]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

humidity_index = X_train.columns.get_loc("humidity")
round(model.coef_[humidity_index], 2)

np.float64(-19810.51)

### Вопрос 7
Оцените качество полученной модели с использованием метрики MSE. Полученное значение округлите до 2 знаков после запятой.

In [35]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

y_pred = model.predict(X_test)

mse = mean_absolute_error(y_test, y_pred)

round(mse, 2)

142635.5

### Вопрос 8
Посмотрим на распределение целевой переменной **resistivity**:

<p align="center">
    <img src="task_8_fig_1.png" alt="Распределение целевой переменной resistivity" width="300">
</p>

Попробуем улучшить качество модели, преобразовав нашу целевую переменную с помощью логарифмирования:

In [36]:
dust_data["lnR"] = np.log(dust_data["resistivity"])

Распределение УЭС пыли (**lnR**) после логарифмирования:

<p align="center">
    <img src="task_8_fig_2.png" alt="Распределение целевой переменной resistivity" width="300">
</p>

Аналогичным образом построим модель линейной регрессии, только теперь в качестве целевой переменной возьмём прологарифмированные значения УЭС пыли (**lnR**):

1. Разделим набор данных на обучающую и тестовую выборки.

In [37]:
X = dust_data.drop(columns=["resistivity", "lnR"])
y = dust_data["lnR"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

2. Выполним создание и обучение модели линейной регрессии.

In [38]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

В качестве ответа укажите значение коэффициента при параметре **dust_dispersiveness**, округлённое до 2 знаков после запятой.

In [39]:
dust_dispersiveness_coef = model.coef_[X.columns.get_loc("temperature")]

round(dust_dispersiveness_coef, 2)

np.float64(-0.05)

### Вопрос 9
Оцените качество полученной модели с использованием метрики MAE. Полученное значение округлите до 2 знаков после запятой.

In [40]:
from sklearn.metrics import mean_absolute_error

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)

round(mae, 2)

2.96

### Вопрос 10
Попробуем добавить еще несколько признаков, используя исходные столбцы:

In [41]:
dust_data["temperature2"] = dust_data["temperature"] ** 2
dust_data["humidityIn"] = 1 / dust_data["humidity"]
dust_data["Lndensity"] = np.log(dust_data["density"])

Построим обновлённую модель с помощью библиотеки `statsmodels` для возможности оценки статистической значимости коэффициентов:

1. Разделим набор данных на обучающую и тестовую выборки.

In [42]:
import statsmodels.api as sm

X = dust_data.drop(columns=["resistivity", "lnR"])
X = sm.add_constant(X)
y = dust_data["lnR"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

2. Выполним создание и обучение модели линейной регрессии.

In [43]:
model = sm.OLS(y_train, X_train)

res = model.fit()

В качестве ответа укажите значение коэффициента при параметре **humidity**, округлённое до 2 знаков после запятой.

In [44]:
round(res.params["density"], 2)

np.float64(-0.01)

### Вопрос 11
На тестовом наборе данных оцените качество модели с использованием метрики MSE. Полученное значение округлите до 2 знаков после запятой.

In [45]:
y_pred = res.predict(X_test)

mse = mean_absolute_error(y_test, y_pred)

round(mse, 2)

2.43

### Вопрос 12
Продолжим улучшать модель линейной регрессии, построенной с помощью библиотеки `statsmodels`. После вывода результатов моделирования с помощью метода `summary()` мы получили таблицу с основной информацией об обученной модели. Для отбора параметров нас будет интересовать вторая таблица с информацией по каждому коэффициенту. Рассмотрим столбец $P > |t|$, содержащий значение *p-value* для проверки нулевой гипотезы о том, что коэффициент = 0. Если значение меньше уровня значимости, это указывает на наличие статистически значимой связи между данным предиктором и целевой переменной.

Построим обновлённую модель, где в качестве предикторов используются только те признаки, коэффициенты перед которыми статистически значимы на уровне значимости $\alpha = 0.05$. В качестве целевой переменной так же будем использовать прологарифмированное значение УЭС пыли (**lnR**).

1. Выберем предикторы, подходящие под условие задачи.

In [46]:
p_values = res.pvalues

significant_vars = p_values[p_values < 0.05].index

2. Разделим набор данных на обучающую и тестовую выборки.

In [47]:
X = dust_data.drop(columns=["resistivity", "lnR"])[significant_vars]
X = sm.add_constant(X)
y = dust_data["lnR"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

3. Выполним создание и обучение модели линейной регрессии.

In [48]:
model = sm.OLS(y_train, X_train)

res = model.fit()

В качестве ответа укажите значение коэффициента перед параметром **humidityIn**, округлённое до 2 знаков после запятой.

In [49]:
round(res.params["formation"], 2)

np.float64(-1.59)

### Вопрос 13
На тестовом наборе данных оцените качество модели с использованием метрики $R^2$. Полученное значение округлите до 2 знаков после запятой.

In [50]:
from sklearn.metrics import r2_score

y_pred = res.predict(X_test)

r2 = mean_absolute_error(y_test, y_pred)

round(r2, 2)

2.45

### Вопрос 14
С использованием последней модели выполним предсказание УЭС пыли при $\text{temperature} = 25$, $\text{humidity} = 2.5$, $\text{humidityIn} = 0.4$, $\text{density} = 1290$, $\text{conductivity} = 2$, $\text{formation} = 1$. Полученное значение округлите до 2 знаков после запятой.

Не забудьте провести обратное преобразование, чтобы перейти от **lnR** к **resistivity**: $\text{resistivity} = e^{lnR}$

In [55]:
input_dust = pd.DataFrame({
    "temperature":  [23],
    "humidity":     [2.6],
    "density":      [1291],
    "conductivity": [2.76],
    "formation":    [2],
    "humidityIn":   [0.38],
})
input_dust = sm.add_constant(input_dust, has_constant="add")

resistivity_ln = res.predict(input_dust)[0]

resistivity = np.exp(resistivity_ln)

round(resistivity, 2)

np.float64(861.06)

In [ ]:
resistivity_ln

np.float64(1368.9592114241111)

In [54]:
res.params

const            6.099698
temperature     -0.052897
humidity        -0.232599
density         -0.002541
conductivity     1.035676
formation       -1.590212
humidityIn      16.006796
dtype: float64

### Вопрос 15
Выберите выводы, которые можно сделать на основании проведённого анализа:

*Варианты ответа:*

1. самой лучшей моделью линейной регрессии всегда будет та, где в качестве предикторов выступают все признаки;
2. перед построением модели линейной регрессии необходимо обязательно выполнить кодирование категориальных признаков;
3. инженерия признаков позволяет улучшить качество модели;
4. различные виды преобразований, например, логарифмирование можно осуществлять только над предикторами, но не целевой переменной.

*Ответ:* 2, 3